services:
  db:
    image: postgres:18
    container_name: cogito_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "cogito_db"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  pgdata: